sato_movies_admin_newsletter:
    resource: "@SatoMoviesBundle/Resources/config/routing/newsletter.yml"
    prefix:   /admin/newsletter

sato_movies_admin_genre:
    resource: "@SatoMoviesBundle/Resources/config/routing/genre.yml"
    prefix:   /admin/genre

sato_movies_admin_contact:
    resource: "@SatoMoviesBundle/Resources/config/routing/contact.yml"
    prefix:   /admin/contact

sato_movies_admin_distributor:
    resource: "@SatoMoviesBundle/Resources/config/routing/distributor.yml"
    prefix:   /admin/distributor

sato_movies_admin_movie:
    resource: "@SatoMoviesBundle/Resources/config/routing/movie.yml"
    prefix:   /admin/movie

sato_movies_admin_actor:
    resource: "@SatoMoviesBundle/Resources/config/routing/actor.yml"
    prefix:   /admin/actor

sato_movies_admin_director:
    resource: "@SatoMoviesBundle/Resources/config/routing/director.yml"
    prefix:   /admin/director

sato_movies_admin_homepage:
    path:     /admin
    defaults: { _controller: SatoMoviesBundle:Admin:index }

sato_movies_homepage:
    path:     /
    defaults: { _controller: SatoMoviesBundle:Default:index }

sato_movies_movie_show:
    path:     /movie/{id}
    defaults: { _controller: SatoMoviesBundle:Default:show }

sato_movies_contact:
    path:     /contact
    defaults: { _controller: SatoMoviesBundle:Default:contact }

sato_movies_about:
    path:     /about
    defaults: { _controller: SatoMoviesBundle:Default:about }

sato_movies_newsletter_save:
    pattern:  /insert/newsletter
    defaults: { _controller: SatoMoviesBundle:Newsletter:save }
    requirements: { _method: post }