sato_movies_admin_movie:
    resource: "@SatoMoviesBundle/Resources/config/routing/movie.yml"
    prefix:   /admin/movie

sato_movies_admin_actor:
    resource: "@SatoMoviesBundle/Resources/config/routing/actor.yml"
    prefix:   /admin/actor

sato_movies_admin_director:
    resource: "@SatoMoviesBundle/Resources/config/routing/director.yml"
    prefix:   /admin/director

sato_movies_admin_homepage:
    path:     /admin
    defaults: { _controller: SatoMoviesBundle:Admin:index }

sato_movies_homepage:
    path:     /
    defaults: { _controller: SatoMoviesBundle:Default:index }

sato_movies_contact:
    path:     /contact
    defaults: { _controller: SatoMoviesBundle:Default:contact }

sato_movies_about:
    path:     /about
    defaults: { _controller: SatoMoviesBundle:Default:about }